### ISSUE TITLE
Push the image to repo

### ISSUE THREAD

**Issue by 99003722** [99003724/LTTS722-727#4]
State:
![State Diagram(In-Built Function)](https://user-images.githubusercontent.com/78848562/107875685-5a837f00-6ee7-11eb-9629-ff9064a72354.png)
Object:
![Object Diagram(inbuilt function)](https://user-images.githubusercontent.com/78848562/107875693-640ce700-6ee7-11eb-9b71-18550bba448c.png)
Deployment:
![Deployment Diagram In Build Diagram](https://user-images.githubusercontent.com/78848562/107875700-6ec77c00-6ee7-11eb-9c3d-0081dad57d0f.png)

**Comment by 99003725** [comment]
updated with my umls
